# Generated by Django 5.1.4 on 2025-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('phone', models.IntegerField(max_length=12)),
            ],
        ),
    ]
