# Generated by Django 5.0.3 on 2025-09-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
